---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-sample-app-drupal-example-db
  annotations:
    flux.weave.works/ignore: "true"
  labels:
    app: stateful-sample-app-drupal-example-db
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeAttributes:
      encryptInTransit: "true"
    volumeHandle: fs-dfee8c5c:/stateful-sample-app-drupal-example-db
