---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: ops
  annotations:
    flux.weave.works/ignore: "true"
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.7
spec:
  chart:
    repository: https://charts.bitnami.com/bitnami/
    name: external-dns
    version: 2.22.1
  helmVersion: v3
  values:
    image:
      registry: docker.io
      repository: bitnami/external-dns
      tag: 0.7.6
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
    aws:
      zoneType: "public"
    domainFilters: ["sandbox-k8s.hobsonsdev.net"]
    txtOwnerId: "tf-platform-k8s-sandbox-ops-external-dns"
    policy: sync
    rbac:
      create: true
      apiVersion: v1
      serviceAccountAnnotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::452534275406:role/tf-platform-k8s-sandbox-ops-external-dns
