apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "ops"
bases:
- ../../../bases/bottlerocket-update-operator
images:
# Before upgrading, check https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/54e5c869b43dc38503fcc862b1cb57e5d073bbbc/update-operator.yaml
- name: 328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-update-operator
  newName: 328549459982.dkr.ecr.us-east-1.amazonaws.com/bottlerocket-update-operator
  newTag: v0.1.4
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: update-operator-controller
    namespace: ops
  path: ./update-operator-controller-deploy-overrides.yaml