apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: stateful-sample-app-drupal-mysql-pass
  labels:
    app: stateful-sample-app-drupal-example
    app.hobsons.io/github-src-repo: platform-core-k8s-ops-workspaces
    app.hobsons.io/maintenance-contact: dl-platform-k8s
    app.hobsons.io/owner-contact: dl-platform-k8s
    app.hobsons.io/product-component: platform
    app.hobsons.io/product-line: platform-sample-apps
    app.hobsons.io/provisioner: fluxcd-kustomize
    app.kubernetes.io/component: platform
    app.kubernetes.io/managed-by: fluxcd-kustomize
    app.kubernetes.io/part-of: platform-sample-apps
spec:
  backendType: secretsManager
  data:
    - key: tf-platform-k8s-sandbox/ops-managed/stateful-sample-app-drupal-mysql-pass
      name: password
      property: password
