namespace: "ops-managed"
resources:
- external-secret.yaml
- ../../../bases/stateful-sample-app-drupal-example
- ingress.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: stateful-sample-app-drupal-example
  path: ./override-deploy-configs.yaml
- target:
    group: ""
    version: v1
    kind: PersistentVolume
    name: stateful-sample-app-drupal-example
  path: ./override-frontend-pv-configs.yaml
- target:
    group: ""
    version: v1
    kind: PersistentVolume
    name: stateful-sample-app-drupal-example-db
  path: ./override-backend-pv-configs.yaml
