---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: ops
  annotations:
    flux.weave.works/ignore: "true"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:v0.3.*
spec:
  chart:
    repository: https://charts.helm.sh/stable
    name: metrics-server
    version: 2.8.9
  helmVersion: v3
  values:
    rbac:
      create: true
    image:
      repository: gcr.io/google_containers/metrics-server-amd64
      tag: v0.3.6
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 32Mi
