resources:
  - github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=v1.3.2
  - efs-storage-class.yaml
patches:
- target:
    kind: DaemonSet
    name: efs-csi-node
    namespace: kube-system
  patch: |-
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: efs-csi-node
      namespace: ops
      annotations:
        fluxcd.io/automated: "false"

    spec:
      template:
        spec:
          priorityClassName: ""
