apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: um-newrelic-license-key
  namespace: ops
  labels:
    app.kubernetes.io/name: newrelic-keys
    app.kubernetes.io/instance: newrelic-keys-ops
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: ops
    app.kubernetes.io/managed-by: fluxcd
    app.hobsons.io/env-name: sandbox
    app.hobsons.io/env-type: sandbox
    app.hobsons.io/product-line: platform
    app.hobsons.io/product-component: k8s
    app.hobsons.io/provisioner: fluxcd
    app.hobsons.io/owner-contact: dl-platform-k8s
    app.hobsons.io/maintenance-contact: dl-platform-k8s
spec:
  backendType: secretsManager
  data:
    - key: tf-platform-k8s-sandbox/ops/um-newrelic-license-key
      name: license-key
      property: license-key
    - key: tf-platform-k8s-sandbox/ops/um-newrelic-license-key
      name: license-key-id
      property: license-key-id