namespace: "ops-managed"
resources:
- ../../../bases/sample-app-flagger-nginx-ingress-prometheus-example
patchesStrategicMerge:
- deployment.yaml
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: sample-app-flagger-nginx-ingress-prometheus-example
  path: ./ingress.yaml
