apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: datadog-keys
  namespace: ops
  labels:
    app.kubernetes.io/name: datadog-keys
    app.kubernetes.io/instance: datadog-keys-ops
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: ops
    app.kubernetes.io/managed-by: fluxcd
    app.hobsons.io/env-name: sandbox
    app.hobsons.io/env-type: sandbox
    app.hobsons.io/product-line: platform
    app.hobsons.io/product-component: k8s
    app.hobsons.io/provisioner: fluxcd
    app.hobsons.io/owner-contact: dl-platform-k8s
    app.hobsons.io/maintenance-contact: dl-platform-k8s
spec:
  backendType: secretsManager
  data:
    - key: tf-platform-k8s-sandbox/ops/datadog-keys
      name: api-key
      property: api-key
    - key: tf-platform-k8s-sandbox/ops/datadog-keys
      name: app-key
      property: app-key
    - key: tf-platform-k8s-sandbox/ops/datadog-keys
      name: token
      property: token
    - key: tf-platform-k8s-sandbox/ops/datadog-keys
      name: DD_API_KEY
      property: api-key
    - key: tf-platform-k8s-sandbox/ops/datadog-keys
      name: DD_APP_KEY
      property: app-key
