apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    flux.weave.works/ignore: "true"
    eks.amazonaws.com/role-arn: arn:aws:iam::452534275406:role/tf-platform-k8s-sandbox-ops-ack-s3-controller-unmanaged
  name: ack-s3-controller