apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: flagger-datadog-key
  annotations:
    flux.weave.works/ignore: "true"
  labels:
    app.kubernetes.io/name: flagger-datadog-key
    app.kubernetes.io/instance: flagger-datadog-key
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: ops
    app.kubernetes.io/managed-by: fluxcd
    app.hobsons.io/env-name: sandbox
    app.hobsons.io/env-type: sandbox
    app.hobsons.io/product-line: platform
    app.hobsons.io/product-component: k8s
    app.hobsons.io/provisioner: fluxcd
    app.hobsons.io/owner-contact: dl-platform-k8s
    app.hobsons.io/maintenance-contact: dl-platform-k8s
spec:
  backendType: secretsManager
  data:
    - key: tf-platform-k8s-sandbox/ops-managed/flagger-datadog-key
      name: datadog_api_key
      property: datadog_api_key
    - key: tf-platform-k8s-sandbox/ops-managed/flagger-datadog-key
      name: datadog_application_key
      property: datadog_application_key
