# THIS FILE IS AUTOMATICALLY GENERATED BY A TERRAFORM TEMPLATE - DO NOT MODIFY DIRECTLY
on:
  push:
    branches:
      - release
  pull_request:
    paths:
      - '.github/workflows/*${workspace}.yaml'
      - 'k8s/${workspace}/**'
      - 'k8s/kustomize/bases/**'
      - 'k8s/kustomize/overlays/${workspace}/**'
name: Workspace - ${workspace} - Manifest Validation
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: kubeval
        uses: stefanprodan/kube-tools@${kube_tools_version}
        with:
          kubectl: ${kubectl_version}
          kustomize: ${kustomize_version}
          command: |
            kubeval --exit-on-error --ignore-missing-schemas  -v ${kubectl_version} -d k8s/${workspace}/
%{ if length(kustomize_build_commands) > 0 }
%{~ for v in kustomize_build_commands ~}
            ${v}

%{~ endfor ~}
%{ endif ~}
# Currently Disabled - see https://github.com/stefanprodan/hrval-action/issues/58
#  hrval:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: hrval k8s/${workspace}/
#        uses: stefanprodan/hrval-action@v${hrval_version}
#        with:
#          kubernetesVersion: ${kubectl_version}
#          helmRelease: k8s/${workspace}/
