namespace: "ops"
resources:
- ../../../bases/flagger
- ./external-secret.yaml
patchesJson6902:
- target:
    group: ""
    version: v1
    kind: PersistentVolume
    name: flagger-prometheus
  path: ./override-flagger-prometheus-pv-configs.yaml
