commonLabels:
  app.kubernetes.io/name: kustomize-platform-k8s-go-sample-app-nginx-ingress-example
  app.kubernetes.io/instance: kustomize-platform-k8s-go-sample-app-nginx-ingress-example
  app.kubernetes.io/component: platform
  app.kubernetes.io/part-of: platform-sample-apps
  app.kubernetes.io/managed-by: fluxcd-kustomize
  app.hobsons.io/product-line: platform-sample-apps
  app.hobsons.io/product-component: platform
  app.hobsons.io/provisioner: fluxcd-kustomize
  app.hobsons.io/owner-contact: dl-platform-k8s
  app.hobsons.io/maintenance-contact: dl-platform-k8s
  app.hobsons.io/github-src-repo: platform-core-k8s-ops-workspaces
resources:
- deployment.yml
- service.yml
