---
apiVersion: v1
kind: Service
metadata:
  annotations:
    flux.weave.works/ignore: "true"
  name: platform-k8s-go-sample-app-nginx-ingress-example
  labels:
    app: platform-k8s-go-sample-app-nginx-ingress-example
    app.kubernetes.io/name: platform-k8s-go-sample-app-nginx-ingress-example
    app.kubernetes.io/instance: platform-k8s-go-sample-app-nginx-ingress-example
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: platform-k8s-go-sample-app-nginx-ingress-example
