---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flagger-prometheus
  annotations:
    flux.weave.works/ignore: "true"
  labels:
    app: flagger-prometheus
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
