resources:
  - github.com/weaveworks/flagger/kustomize/base/flagger?ref=v1.7.0
  - github.com/weaveworks/flagger/kustomize/base/prometheus?ref=v1.7.0
  - github.com/weaveworks/flagger/kustomize/tester/?ref=v1.7.0
  - alertprovider.yaml
  - flagger-prometheus-pv.yaml
  - flagger-prometheus-pvc.yaml
patches:
- target:
    kind: Deployment
    name: flagger
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: flagger
    spec:
      template:
        spec:
          containers:
          - name: flagger
            args:
              - -log-level=debug
              - -mesh-provider=nginx
              - -metrics-server=http://flagger-prometheus:9090
              - -slack-user=flagger
              - -slack-channel=test-flagger-alerts
              - -slack-url=""
            resources:
              requests:
                cpu: 100m
                memory: 90Mi
- target:
    kind: Deployment
    name: flagger-prometheus
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: flagger-prometheus
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 10002
            runAsGroup: 10002
            fsGroup: 10002        
          containers:
          - name: prometheus
            args:
            - --storage.tsdb.retention.time=15d
            - --storage.tsdb.no-lockfile
            - --config.file=/etc/prometheus/prometheus.yml
            resources:
              limits:
                cpu: 400m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 1024Mi
            volumeMounts:
              - name: config-volume
                mountPath: /etc/prometheus
              - name: persistent-data-volume
                mountPath: /prometheus/data
          volumes:
            - name: persistent-data-volume
              persistentVolumeClaim:
                claimName: flagger-prometheus
